[package]
name = "synchron"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[[bin]]
name = "synchron"
path = "src/main.rs"
