[package]
name = "synchron-ffi"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.22.0"
