[target.x86_64-unknown-linux-gnu]
linker = "gcc"
ar = "ar"

[target.i686-unknown-linux-gnu]
linker = "gcc"
ar = "ar"
rustflags = ["-C", "link-arg=-m32"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-gcc-ar"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
ar = "i686-w64-mingw32-gcc-ar"
