[package]
name = "synchron-common"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }

